const ACTIONS = {
  //logIn
  AUTH_REQUEST: "AUTH_REQUEST",
  AUTH_SUCCESS: "AUTH_SUCCESS",
  AUTH_FAILURE: "AUTH_FAILURE",

  //SignUp
  AUTH_SIGNUP_REQUEST :"AUTH_SIGNUP_REQUEST",
  AUTH_SIGNUP_SUCCESS :"AUTH_SIGNUP_SUCCESS",
  AUTH_SIGNUP_FAILURE :"AUTH_SIGNUP_FAILURE"
}
export default ACTIONS
